apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: smtrack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: siamatic/smtrack-frontend:1.0.0b
          ports:
            - containerPort: 7258
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 100m
